Uptime KPI Slack Alerts, Logging & Data Assurance
Kyoto-Cognite/kyoto-functions pull request #25
Opened 2024-07-15 13:59 UTC by DamianBudelewski200

If Uptime Calculation fails, it should send alert on Kyoto slack.

# Todo

- [x] Add ENV variable for SLACK_URL before merge

2024-07-15 14:27 UTC, PatrykKotOrder commented on fn_uptime_data_generator/handler.py
> +        return {"status": "failed", "date": today.isoformat(), "cause": e}
you have try except in function insert_uptime_kpi which will catch all Exceptions so this one will not catch anything.
Maybe yo need to narrow down errors one level deeper or "raise" after logging by sentry

2024-07-15 14:27 UTC, PatrykKotOrder commented on fn_uptime_data_generator/uptime.py
> +    except Exception as e:
I ment here to maybe narrow down Exception or  after log raise it again that next will catch

2024-07-15 14:43 UTC, DamianBudelewski200 commented on fn_uptime_data_generator/uptime.py
> +    except Exception as e:
I'm not sure if I understood you correctly, but please take a look at the newest changes and if this is what you proposed.

2024-07-16 08:29 UTC, DamianBudelewski200 commented
Pre commit is now passing for the folders with changes.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/31a87a33-c7e2-4107-adc9-76ce8d87cfa5">

2024-07-17 07:33 UTC, DamianBudelewski200 commented
@pcperera 

I've added a secret to the repo for main environment. I tried to follow the naming convention `EXTRA_SECRETS_fn_uptime_data_generator` but the GitHub UI automatically changed it to uppercase.

<img width="805" alt="image" src="https://github.com/user-attachments/assets/c787805d-b739-46a5-9552-0c4433b18748">

1. So I think this should also be modified inside the `.github/workflows/deploy-functions-prod.yaml` right?

```
      - name: Extra secrets
        if: ${{ contains(needs.generate-matrix.outputs.deploy_folders, matrix.function) }}
        shell: bash
        # Secret name should be EXTRA_SECRETS_{function name} (if applicable)
        run: |
          echo "extra_secrets_name=EXTRA_SECRETS_${{ matrix.function }}" >> $GITHUB_OUTPUT
        id: extract_secrets

```

2. How can I then use this secret inside the function? 

Is it a env var?

That's the dict I created:

```
{
	"errors-slack-webhook-url": "https://hooks.slack.com/services/......"
}
```

2024-07-17 07:36 UTC, DamianBudelewski200 commented
@PatrykKotOrder Why for this function cdf_project_name is a hardcoded value?

```
cdf_project_name = "kyotogroup-dev"  # os.environ["CDF_PROJECT"]
```
Other functions have

```
cdf_project_name = os.environ["KYOTO_CDF_PROJECT"]
```

2024-07-23 01:31 UTC, pcperera requested changes
handle() function the entry point for Cognite functiions.

https://docs.cognite.com/de/cdf/functions/

2024-07-24 08:43 UTC, DamianBudelewski200 commented
@pcperera btw, do we need `data` argument in `handle` function? If we don't pass anything?

2024-07-25 06:48 UTC, pcperera commented on pyproject.toml
> +requests = "^2.32.3"
CDF will use dependencies read from requirements.txt so it will needed to be updated.

2024-07-25 07:47 UTC, DamianBudelewski200 commented on pyproject.toml
> +requests = "^2.32.3"
nice catch. added. In both places, uptime and common (because slack function is using it) is this correct? Should it be only in common, or in uptime, or in both folders?

2024-07-25 08:33 UTC, pcperera commented on pyproject.toml
> +requests = "^2.32.3"
Each function has a requirements.txt. common doesn't need a requirements.txt since that's not a function

2024-07-25 08:42 UTC, DamianBudelewski200 commented on pyproject.toml
> +requests = "^2.32.3"
ok, removed

2024-07-25 08:44 UTC, DamianBudelewski200 commented on .pre-commit-config.yaml
> +        additional_dependencies: ['types-requests', 'pandas-stubs']
@pcperera What about this? Have you encountered the same problem elsewhere? 

I got those two errors when trying to commit:
        # Fix for: common/slack.py:3: error: Library stubs not installed for "requests"  [import-untyped]
        # Fix for: fn_uptime_data_generator/uptime.py:3: error: Library stubs not installed for "pandas"  [import-untyped]

Couldn't fix this by installing those libraries.

2024-07-25 08:47 UTC, pcperera commented
> @pcperera
> 
> I've added a secret to the repo for main environment. I tried to follow the naming convention `EXTRA_SECRETS_fn_uptime_data_generator` but the GitHub UI automatically changed it to uppercase.
> 
> <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/142970910/349401356-c787805d-b739-46a5-9552-0c4433b18748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTY2MTcsIm5iZiI6MTcyMTg5NjMxNywicGF0aCI6Ii8xNDI5NzA5MTAvMzQ5NDAxMzU2LWM3ODc4MDVkLWI3MzktNDZhNS05NTUyLTBjNDQzM2IxODc0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwODMxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzc1NjUxMzdlM2Y0MTk4MmQxMzcwOWE3YzhkMDg0MTA1NmVhYmMwZDQ2MTNmYWUxYTk5M2VjNmU3YTBiNjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XDric3MCtGQ_w-9EkrCQkyESAKsE1RUmYMfVpsmOS2s">
> 1. So I think this should also be modified inside the `.github/workflows/deploy-functions-prod.yaml` right?
> 
> ```
>       - name: Extra secrets
>         if: ${{ contains(needs.generate-matrix.outputs.deploy_folders, matrix.function) }}
>         shell: bash
>         # Secret name should be EXTRA_SECRETS_{function name} (if applicable)
>         run: |
>           echo "extra_secrets_name=EXTRA_SECRETS_${{ matrix.function }}" >> $GITHUB_OUTPUT
>         id: extract_secrets
> ```
> 
> 2. How can I then use this secret inside the function?
> 
> Is it a env var?
> 
> That's the dict I created:
> 
> ```
> {
> 	"errors-slack-webhook-url": "https://hooks.slack.com/services/......"
> }
> ```

The secrets needs to be added to https://github.com/TotalEnergies-Cognite/toolkit/settings in the GitHub environment

2024-07-25 09:34 UTC, pcperera approved these changes

2024-07-25 09:35 UTC, merged